name: Upload Docker images

permissions:
  packages: write      

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Docker Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables
        id: vars
        run: echo "::set-output name=date_tag::$(date +%y%m%d-%H%M)"

      - name: Docker Buildx Create
        run: docker buildx create --use

      - name: Build and push build-su2
        uses: docker/build-push-action@v2
        with:
          context: build
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/su2/build-su2:${{ steps.vars.outputs.date_tag }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push test-su2
        uses: docker/build-push-action@v2
        with:
          context: test
          push: true
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/su2/build-su2:${{ steps.vars.outputs.date_tag }}
          tags: ghcr.io/${{ github.repository_owner }}/su2/test-su2:${{ steps.vars.outputs.date_tag }}
          platforms: linux/amd64,linux/arm64
